### ISSUE TITLE
Standardising platform labels

### ISSUE THREAD

**Issue by Pixxel123** [TheKersalMassive/ReskinPS5#39]
It seems that with Sony PlayStation consoles, the full names are as follows:

> Sony PlayStation 2
> Sony Playstation 3
> Sony PlayStation 4
> Sony PlayStation 5
> Sony PlayStation
> Sony PlayStation Portable
> Sony PlayStation Vita

The values used by the theme for the labels on the game covers use:

Playstation 2
Playstation 3
Playstation 4
Playstation 5
Playstation
Playstation Portable
Playstation Vita

It may be worth standardising these, given that Nintendo consoles use Nintendo Switch and Nintendo Wii U for example, and also others like Sega Dreamcast, XBOX Games Pass, XBOX Series X (which should be Microsoft Xbox, Microsoft Xbox Series X, etc).

If we have a clear template, for example: `[Company] [Console Name & generation]` it would make things cleaner.

**Comment by TheKersalMassive** [comment]
I was hoping no one would point this out but knew this was coming :)

So I've based the labels on what I have named the platforms rather than what Playnite has named them as default.

I might change to read the Platform ID instead, so they match the Playnite selected platform specification regardless of what the platform name is set by the user, such as below:

![image](https://user-images.githubusercontent.com/90322803/183310685-77372958-e78b-4470-9847-b1b82707cb69.png)

**Comment by TheKersalMassive** [comment]
Changed labels to read the Platform Specification instead of Platform name.

**Comment by TheKersalMassive** [comment]
Made a change again, decided to let users upload their own icons in the Library manager instead of trying to define the platform spec in the filename, which can be difficult if they don't know what the spec ID is.

Will be in v1.11
